### ISSUE TITLE
filtering by event category

### ISSUE THREAD

**Issue by szmeku** [szmeku/ultramarynia#2]
- each category should have time background in different color
- put chips at the of the page with categories that clicked would filter out appropriately (use same colors)

![image](https://github.com/szmeku/ultramarynia/assets/1058036/56e6b4cc-adf9-43c2-8b2d-adce312162d8)

Colors
```css
.visible-yellow { background-color: #FAD02E; }
.visible-orange { background-color: #F28D35; }
.visible-pink { background-color: #EA5F89; }
.visible-blue { background-color: #8B8BF0; }
.visible-green { background-color: #6ECB63; }
.visible-rose { background-color: #FE88B1; }
.visible-turquoise { background-color: #00B7C2; }
.visible-amber { background-color: #FCAB10; }
.visible-lilac { background-color: #9878F3; }
.visible-cyan { background-color: #3BCEDA; }
```
